// proto/kari/agent/v1/agent.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/kari/agent/v1/agent.proto

package rustagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceAction int32

const (
	ServiceAction_START   ServiceAction = 0
	ServiceAction_STOP    ServiceAction = 1
	ServiceAction_RESTART ServiceAction = 2
	ServiceAction_RELOAD  ServiceAction = 3
	ServiceAction_ENABLE  ServiceAction = 4
	ServiceAction_DISABLE ServiceAction = 5
)

// Enum value maps for ServiceAction.
var (
	ServiceAction_name = map[int32]string{
		0: "START",
		1: "STOP",
		2: "RESTART",
		3: "RELOAD",
		4: "ENABLE",
		5: "DISABLE",
	}
	ServiceAction_value = map[string]int32{
		"START":   0,
		"STOP":    1,
		"RESTART": 2,
		"RELOAD":  3,
		"ENABLE":  4,
		"DISABLE": 5,
	}
)

func (x ServiceAction) Enum() *ServiceAction {
	p := new(ServiceAction)
	*p = x
	return p
}

func (x ServiceAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kari_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (ServiceAction) Type() protoreflect.EnumType {
	return &file_proto_kari_agent_v1_agent_proto_enumTypes[0]
}

func (x ServiceAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceAction.Descriptor instead.
func (ServiceAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type FirewallPolicy_Action int32

const (
	FirewallPolicy_ALLOW  FirewallPolicy_Action = 0
	FirewallPolicy_DENY   FirewallPolicy_Action = 1
	FirewallPolicy_REJECT FirewallPolicy_Action = 2
)

// Enum value maps for FirewallPolicy_Action.
var (
	FirewallPolicy_Action_name = map[int32]string{
		0: "ALLOW",
		1: "DENY",
		2: "REJECT",
	}
	FirewallPolicy_Action_value = map[string]int32{
		"ALLOW":  0,
		"DENY":   1,
		"REJECT": 2,
	}
)

func (x FirewallPolicy_Action) Enum() *FirewallPolicy_Action {
	p := new(FirewallPolicy_Action)
	*p = x
	return p
}

func (x FirewallPolicy_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FirewallPolicy_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kari_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (FirewallPolicy_Action) Type() protoreflect.EnumType {
	return &file_proto_kari_agent_v1_agent_proto_enumTypes[1]
}

func (x FirewallPolicy_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FirewallPolicy_Action.Descriptor instead.
func (FirewallPolicy_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{4, 0}
}

type FirewallPolicy_Protocol int32

const (
	FirewallPolicy_TCP  FirewallPolicy_Protocol = 0
	FirewallPolicy_UDP  FirewallPolicy_Protocol = 1
	FirewallPolicy_BOTH FirewallPolicy_Protocol = 2
)

// Enum value maps for FirewallPolicy_Protocol.
var (
	FirewallPolicy_Protocol_name = map[int32]string{
		0: "TCP",
		1: "UDP",
		2: "BOTH",
	}
	FirewallPolicy_Protocol_value = map[string]int32{
		"TCP":  0,
		"UDP":  1,
		"BOTH": 2,
	}
)

func (x FirewallPolicy_Protocol) Enum() *FirewallPolicy_Protocol {
	p := new(FirewallPolicy_Protocol)
	*p = x
	return p
}

func (x FirewallPolicy_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FirewallPolicy_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kari_agent_v1_agent_proto_enumTypes[2].Descriptor()
}

func (FirewallPolicy_Protocol) Type() protoreflect.EnumType {
	return &file_proto_kari_agent_v1_agent_proto_enumTypes[2]
}

func (x FirewallPolicy_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FirewallPolicy_Protocol.Descriptor instead.
func (FirewallPolicy_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{4, 1}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type SystemStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Healthy         bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ActiveJails     uint32                 `protobuf:"varint,2,opt,name=active_jails,json=activeJails,proto3" json:"active_jails,omitempty"`
	CpuUsagePercent float32                `protobuf:"fixed32,3,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsageMb   float32                `protobuf:"fixed32,4,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	UptimeSeconds   uint64                 `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SystemStatus) Reset() {
	*x = SystemStatus{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatus) ProtoMessage() {}

func (x *SystemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatus.ProtoReflect.Descriptor instead.
func (*SystemStatus) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SystemStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *SystemStatus) GetActiveJails() uint32 {
	if x != nil {
		return x.ActiveJails
	}
	return 0
}

func (x *SystemStatus) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *SystemStatus) GetMemoryUsageMb() float32 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

func (x *SystemStatus) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *SystemStatus) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type AgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *AgentResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *AgentResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *AgentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 🛡️ Real-time observability payload for SvelteKit SSE
type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // Raw ANSI output from the Rust sub-process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *LogChunk) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type FirewallPolicy struct {
	state    protoimpl.MessageState  `protogen:"open.v1"`
	Action   FirewallPolicy_Action   `protobuf:"varint,1,opt,name=action,proto3,enum=kari.agent.v1.FirewallPolicy_Action" json:"action,omitempty"`
	Port     uint32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // Validated in Rust as 1-65535
	Protocol FirewallPolicy_Protocol `protobuf:"varint,3,opt,name=protocol,proto3,enum=kari.agent.v1.FirewallPolicy_Protocol" json:"protocol,omitempty"`
	// 🛡️ Optional: Enforces strict source-based filtering
	SourceIp      *string `protobuf:"bytes,4,opt,name=source_ip,json=sourceIp,proto3,oneof" json:"source_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallPolicy) Reset() {
	*x = FirewallPolicy{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallPolicy) ProtoMessage() {}

func (x *FirewallPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallPolicy.ProtoReflect.Descriptor instead.
func (*FirewallPolicy) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *FirewallPolicy) GetAction() FirewallPolicy_Action {
	if x != nil {
		return x.Action
	}
	return FirewallPolicy_ALLOW
}

func (x *FirewallPolicy) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *FirewallPolicy) GetProtocol() FirewallPolicy_Protocol {
	if x != nil {
		return x.Protocol
	}
	return FirewallPolicy_TCP
}

func (x *FirewallPolicy) GetSourceIp() string {
	if x != nil && x.SourceIp != nil {
		return *x.SourceIp
	}
	return ""
}

type JobIntent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	JobName string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	// 🛡️ Zero-Trust: Split to prevent shell injection via OS execve
	Binary             string   `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`
	Args               []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	ScheduleExpression string   `protobuf:"bytes,4,opt,name=schedule_expression,json=scheduleExpression,proto3" json:"schedule_expression,omitempty"` // Cron format
	RunAsUser          string   `protobuf:"bytes,5,opt,name=run_as_user,json=runAsUser,proto3" json:"run_as_user,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobIntent) Reset() {
	*x = JobIntent{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobIntent) ProtoMessage() {}

func (x *JobIntent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobIntent.ProtoReflect.Descriptor instead.
func (*JobIntent) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *JobIntent) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *JobIntent) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *JobIntent) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *JobIntent) GetScheduleExpression() string {
	if x != nil {
		return x.ScheduleExpression
	}
	return ""
}

func (x *JobIntent) GetRunAsUser() string {
	if x != nil {
		return x.RunAsUser
	}
	return ""
}

type SslPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainName    string                 `protobuf:"bytes,1,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	FullchainPem  []byte                 `protobuf:"bytes,2,opt,name=fullchain_pem,json=fullchainPem,proto3" json:"fullchain_pem,omitempty"`
	PrivkeyPem    []byte                 `protobuf:"bytes,3,opt,name=privkey_pem,json=privkeyPem,proto3" json:"privkey_pem,omitempty"` // 🛡️ Privacy: Rust agent must zeroize this buffer!
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SslPayload) Reset() {
	*x = SslPayload{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SslPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SslPayload) ProtoMessage() {}

func (x *SslPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SslPayload.ProtoReflect.Descriptor instead.
func (*SslPayload) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SslPayload) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *SslPayload) GetFullchainPem() []byte {
	if x != nil {
		return x.FullchainPem
	}
	return nil
}

func (x *SslPayload) GetPrivkeyPem() []byte {
	if x != nil {
		return x.PrivkeyPem
	}
	return nil
}

type PackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageRequest) Reset() {
	*x = PackageRequest{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageRequest) ProtoMessage() {}

func (x *PackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageRequest.ProtoReflect.Descriptor instead.
func (*PackageRequest) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *PackageRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *PackageRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type FileWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	AbsolutePath  string                 `protobuf:"bytes,2,opt,name=absolute_path,json=absolutePath,proto3" json:"absolute_path,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	FileMode      string                 `protobuf:"bytes,6,opt,name=file_mode,json=fileMode,proto3" json:"file_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteRequest) Reset() {
	*x = FileWriteRequest{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteRequest) ProtoMessage() {}

func (x *FileWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteRequest.ProtoReflect.Descriptor instead.
func (*FileWriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *FileWriteRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *FileWriteRequest) GetAbsolutePath() string {
	if x != nil {
		return x.AbsolutePath
	}
	return ""
}

func (x *FileWriteRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileWriteRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *FileWriteRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FileWriteRequest) GetFileMode() string {
	if x != nil {
		return x.FileMode
	}
	return ""
}

type ServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Action        ServiceAction          `protobuf:"varint,2,opt,name=action,proto3,enum=kari.agent.v1.ServiceAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRequest) Reset() {
	*x = ServiceRequest{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest) ProtoMessage() {}

func (x *ServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest.ProtoReflect.Descriptor instead.
func (*ServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceRequest) GetAction() ServiceAction {
	if x != nil {
		return x.Action
	}
	return ServiceAction_START
}

type ProvisionJailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DomainName    string                 `protobuf:"bytes,2,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	StartCommand  string                 `protobuf:"bytes,3,opt,name=start_command,json=startCommand,proto3" json:"start_command,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,4,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MemoryLimitMb uint32                 `protobuf:"varint,5,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"` // 🛡️ SLA: Hard-limit enforcement
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionJailRequest) Reset() {
	*x = ProvisionJailRequest{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionJailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionJailRequest) ProtoMessage() {}

func (x *ProvisionJailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionJailRequest.ProtoReflect.Descriptor instead.
func (*ProvisionJailRequest) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ProvisionJailRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ProvisionJailRequest) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *ProvisionJailRequest) GetStartCommand() string {
	if x != nil {
		return x.StartCommand
	}
	return ""
}

func (x *ProvisionJailRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *ProvisionJailRequest) GetMemoryLimitMb() uint32 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // Links stream to Dashboard Action Center
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DomainName    string                 `protobuf:"bytes,3,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	RepoUrl       string                 `protobuf:"bytes,4,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Branch        string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	BuildCommand  string                 `protobuf:"bytes,6,opt,name=build_command,json=buildCommand,proto3" json:"build_command,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,7,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Port          *int32                 `protobuf:"varint,8,opt,name=port,proto3,oneof" json:"port,omitempty"`                  // App internal port for proxy
	SshKey        *string                `protobuf:"bytes,9,opt,name=ssh_key,json=sshKey,proto3,oneof" json:"ssh_key,omitempty"` // 🛡️ Privacy: Transient SSH key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DeployRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *DeployRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeployRequest) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *DeployRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *DeployRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *DeployRequest) GetBuildCommand() string {
	if x != nil {
		return x.BuildCommand
	}
	return ""
}

func (x *DeployRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *DeployRequest) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *DeployRequest) GetSshKey() string {
	if x != nil && x.SshKey != nil {
		return *x.SshKey
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DomainName    string                 `protobuf:"bytes,2,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeleteRequest) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

type TeardownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // Links to deployment telemetry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownRequest) Reset() {
	*x = TeardownRequest{}
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownRequest) ProtoMessage() {}

func (x *TeardownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kari_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownRequest.ProtoReflect.Descriptor instead.
func (*TeardownRequest) Descriptor() ([]byte, []int) {
	return file_proto_kari_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *TeardownRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *TeardownRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_proto_kari_agent_v1_agent_proto protoreflect.FileDescriptor

const file_proto_kari_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/kari/agent/v1/agent.proto\x12\rkari.agent.v1\"\a\n" +
	"\x05Empty\"\xeb\x01\n" +
	"\fSystemStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\factive_jails\x18\x02 \x01(\rR\vactiveJails\x12*\n" +
	"\x11cpu_usage_percent\x18\x03 \x01(\x02R\x0fcpuUsagePercent\x12&\n" +
	"\x0fmemory_usage_mb\x18\x04 \x01(\x02R\rmemoryUsageMb\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x04R\ruptimeSeconds\"\x9b\x01\n" +
	"\rAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"?\n" +
	"\bLogChunk\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xa9\x02\n" +
	"\x0eFirewallPolicy\x12<\n" +
	"\x06action\x18\x01 \x01(\x0e2$.kari.agent.v1.FirewallPolicy.ActionR\x06action\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12B\n" +
	"\bprotocol\x18\x03 \x01(\x0e2&.kari.agent.v1.FirewallPolicy.ProtocolR\bprotocol\x12 \n" +
	"\tsource_ip\x18\x04 \x01(\tH\x00R\bsourceIp\x88\x01\x01\")\n" +
	"\x06Action\x12\t\n" +
	"\x05ALLOW\x10\x00\x12\b\n" +
	"\x04DENY\x10\x01\x12\n" +
	"\n" +
	"\x06REJECT\x10\x02\"&\n" +
	"\bProtocol\x12\a\n" +
	"\x03TCP\x10\x00\x12\a\n" +
	"\x03UDP\x10\x01\x12\b\n" +
	"\x04BOTH\x10\x02B\f\n" +
	"\n" +
	"_source_ip\"\xa3\x01\n" +
	"\tJobIntent\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\x12\x16\n" +
	"\x06binary\x18\x02 \x01(\tR\x06binary\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12/\n" +
	"\x13schedule_expression\x18\x04 \x01(\tR\x12scheduleExpression\x12\x1e\n" +
	"\vrun_as_user\x18\x05 \x01(\tR\trunAsUser\"s\n" +
	"\n" +
	"SslPayload\x12\x1f\n" +
	"\vdomain_name\x18\x01 \x01(\tR\n" +
	"domainName\x12#\n" +
	"\rfullchain_pem\x18\x02 \x01(\fR\ffullchainPem\x12\x1f\n" +
	"\vprivkey_pem\x18\x03 \x01(\fR\n" +
	"privkeyPem\">\n" +
	"\x0ePackageRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\xb5\x01\n" +
	"\x10FileWriteRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12#\n" +
	"\rabsolute_path\x18\x02 \x01(\tR\fabsolutePath\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12\x1b\n" +
	"\tfile_mode\x18\x06 \x01(\tR\bfileMode\"i\n" +
	"\x0eServiceRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x124\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1c.kari.agent.v1.ServiceActionR\x06action\"\xa4\x02\n" +
	"\x14ProvisionJailRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1f\n" +
	"\vdomain_name\x18\x02 \x01(\tR\n" +
	"domainName\x12#\n" +
	"\rstart_command\x18\x03 \x01(\tR\fstartCommand\x12K\n" +
	"\benv_vars\x18\x04 \x03(\v20.kari.agent.v1.ProvisionJailRequest.EnvVarsEntryR\aenvVars\x12&\n" +
	"\x0fmemory_limit_mb\x18\x05 \x01(\rR\rmemoryLimitMb\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x03\n" +
	"\rDeployRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1f\n" +
	"\vdomain_name\x18\x03 \x01(\tR\n" +
	"domainName\x12\x19\n" +
	"\brepo_url\x18\x04 \x01(\tR\arepoUrl\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x12#\n" +
	"\rbuild_command\x18\x06 \x01(\tR\fbuildCommand\x12D\n" +
	"\benv_vars\x18\a \x03(\v2).kari.agent.v1.DeployRequest.EnvVarsEntryR\aenvVars\x12\x17\n" +
	"\x04port\x18\b \x01(\x05H\x00R\x04port\x88\x01\x01\x12\x1c\n" +
	"\assh_key\x18\t \x01(\tH\x01R\x06sshKey\x88\x01\x01\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_portB\n" +
	"\n" +
	"\b_ssh_key\"G\n" +
	"\rDeleteRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1f\n" +
	"\vdomain_name\x18\x02 \x01(\tR\n" +
	"domainName\"C\n" +
	"\x0fTeardownRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId*V\n" +
	"\rServiceAction\x12\t\n" +
	"\x05START\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\x12\v\n" +
	"\aRESTART\x10\x02\x12\n" +
	"\n" +
	"\x06RELOAD\x10\x03\x12\n" +
	"\n" +
	"\x06ENABLE\x10\x04\x12\v\n" +
	"\aDISABLE\x10\x052\xf5\x06\n" +
	"\vSystemAgent\x12D\n" +
	"\x0fGetSystemStatus\x12\x14.kari.agent.v1.Empty\x1a\x1b.kari.agent.v1.SystemStatus\x12T\n" +
	"\x15ExecutePackageCommand\x12\x1d.kari.agent.v1.PackageRequest\x1a\x1c.kari.agent.v1.AgentResponse\x12U\n" +
	"\x10ProvisionAppJail\x12#.kari.agent.v1.ProvisionJailRequest\x1a\x1c.kari.agent.v1.AgentResponse\x12L\n" +
	"\rManageService\x12\x1d.kari.agent.v1.ServiceRequest\x1a\x1c.kari.agent.v1.AgentResponse\x12K\n" +
	"\x10StreamDeployment\x12\x1c.kari.agent.v1.DeployRequest\x1a\x17.kari.agent.v1.LogChunk0\x01\x12N\n" +
	"\x10DeleteDeployment\x12\x1c.kari.agent.v1.DeleteRequest\x1a\x1c.kari.agent.v1.AgentResponse\x12L\n" +
	"\fTeardownJail\x12\x1e.kari.agent.v1.TeardownRequest\x1a\x1c.kari.agent.v1.AgentResponse\x12P\n" +
	"\x0fWriteSystemFile\x12\x1f.kari.agent.v1.FileWriteRequest\x1a\x1c.kari.agent.v1.AgentResponse\x12M\n" +
	"\x12InstallCertificate\x12\x19.kari.agent.v1.SslPayload\x1a\x1c.kari.agent.v1.AgentResponse\x12R\n" +
	"\x13ApplyFirewallPolicy\x12\x1d.kari.agent.v1.FirewallPolicy\x1a\x1c.kari.agent.v1.AgentResponse\x12E\n" +
	"\vScheduleJob\x12\x18.kari.agent.v1.JobIntent\x1a\x1c.kari.agent.v1.AgentResponseB@Z>github.com/irgordon/kari/api/internal/grpc/rustagent;rustagentb\x06proto3"

var (
	file_proto_kari_agent_v1_agent_proto_rawDescOnce sync.Once
	file_proto_kari_agent_v1_agent_proto_rawDescData []byte
)

func file_proto_kari_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_kari_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_kari_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kari_agent_v1_agent_proto_rawDesc), len(file_proto_kari_agent_v1_agent_proto_rawDesc)))
	})
	return file_proto_kari_agent_v1_agent_proto_rawDescData
}

var file_proto_kari_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_kari_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_kari_agent_v1_agent_proto_goTypes = []any{
	(ServiceAction)(0),           // 0: kari.agent.v1.ServiceAction
	(FirewallPolicy_Action)(0),   // 1: kari.agent.v1.FirewallPolicy.Action
	(FirewallPolicy_Protocol)(0), // 2: kari.agent.v1.FirewallPolicy.Protocol
	(*Empty)(nil),                // 3: kari.agent.v1.Empty
	(*SystemStatus)(nil),         // 4: kari.agent.v1.SystemStatus
	(*AgentResponse)(nil),        // 5: kari.agent.v1.AgentResponse
	(*LogChunk)(nil),             // 6: kari.agent.v1.LogChunk
	(*FirewallPolicy)(nil),       // 7: kari.agent.v1.FirewallPolicy
	(*JobIntent)(nil),            // 8: kari.agent.v1.JobIntent
	(*SslPayload)(nil),           // 9: kari.agent.v1.SslPayload
	(*PackageRequest)(nil),       // 10: kari.agent.v1.PackageRequest
	(*FileWriteRequest)(nil),     // 11: kari.agent.v1.FileWriteRequest
	(*ServiceRequest)(nil),       // 12: kari.agent.v1.ServiceRequest
	(*ProvisionJailRequest)(nil), // 13: kari.agent.v1.ProvisionJailRequest
	(*DeployRequest)(nil),        // 14: kari.agent.v1.DeployRequest
	(*DeleteRequest)(nil),        // 15: kari.agent.v1.DeleteRequest
	(*TeardownRequest)(nil),      // 16: kari.agent.v1.TeardownRequest
	nil,                          // 17: kari.agent.v1.ProvisionJailRequest.EnvVarsEntry
	nil,                          // 18: kari.agent.v1.DeployRequest.EnvVarsEntry
}
var file_proto_kari_agent_v1_agent_proto_depIdxs = []int32{
	1,  // 0: kari.agent.v1.FirewallPolicy.action:type_name -> kari.agent.v1.FirewallPolicy.Action
	2,  // 1: kari.agent.v1.FirewallPolicy.protocol:type_name -> kari.agent.v1.FirewallPolicy.Protocol
	0,  // 2: kari.agent.v1.ServiceRequest.action:type_name -> kari.agent.v1.ServiceAction
	17, // 3: kari.agent.v1.ProvisionJailRequest.env_vars:type_name -> kari.agent.v1.ProvisionJailRequest.EnvVarsEntry
	18, // 4: kari.agent.v1.DeployRequest.env_vars:type_name -> kari.agent.v1.DeployRequest.EnvVarsEntry
	3,  // 5: kari.agent.v1.SystemAgent.GetSystemStatus:input_type -> kari.agent.v1.Empty
	10, // 6: kari.agent.v1.SystemAgent.ExecutePackageCommand:input_type -> kari.agent.v1.PackageRequest
	13, // 7: kari.agent.v1.SystemAgent.ProvisionAppJail:input_type -> kari.agent.v1.ProvisionJailRequest
	12, // 8: kari.agent.v1.SystemAgent.ManageService:input_type -> kari.agent.v1.ServiceRequest
	14, // 9: kari.agent.v1.SystemAgent.StreamDeployment:input_type -> kari.agent.v1.DeployRequest
	15, // 10: kari.agent.v1.SystemAgent.DeleteDeployment:input_type -> kari.agent.v1.DeleteRequest
	16, // 11: kari.agent.v1.SystemAgent.TeardownJail:input_type -> kari.agent.v1.TeardownRequest
	11, // 12: kari.agent.v1.SystemAgent.WriteSystemFile:input_type -> kari.agent.v1.FileWriteRequest
	9,  // 13: kari.agent.v1.SystemAgent.InstallCertificate:input_type -> kari.agent.v1.SslPayload
	7,  // 14: kari.agent.v1.SystemAgent.ApplyFirewallPolicy:input_type -> kari.agent.v1.FirewallPolicy
	8,  // 15: kari.agent.v1.SystemAgent.ScheduleJob:input_type -> kari.agent.v1.JobIntent
	4,  // 16: kari.agent.v1.SystemAgent.GetSystemStatus:output_type -> kari.agent.v1.SystemStatus
	5,  // 17: kari.agent.v1.SystemAgent.ExecutePackageCommand:output_type -> kari.agent.v1.AgentResponse
	5,  // 18: kari.agent.v1.SystemAgent.ProvisionAppJail:output_type -> kari.agent.v1.AgentResponse
	5,  // 19: kari.agent.v1.SystemAgent.ManageService:output_type -> kari.agent.v1.AgentResponse
	6,  // 20: kari.agent.v1.SystemAgent.StreamDeployment:output_type -> kari.agent.v1.LogChunk
	5,  // 21: kari.agent.v1.SystemAgent.DeleteDeployment:output_type -> kari.agent.v1.AgentResponse
	5,  // 22: kari.agent.v1.SystemAgent.TeardownJail:output_type -> kari.agent.v1.AgentResponse
	5,  // 23: kari.agent.v1.SystemAgent.WriteSystemFile:output_type -> kari.agent.v1.AgentResponse
	5,  // 24: kari.agent.v1.SystemAgent.InstallCertificate:output_type -> kari.agent.v1.AgentResponse
	5,  // 25: kari.agent.v1.SystemAgent.ApplyFirewallPolicy:output_type -> kari.agent.v1.AgentResponse
	5,  // 26: kari.agent.v1.SystemAgent.ScheduleJob:output_type -> kari.agent.v1.AgentResponse
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_kari_agent_v1_agent_proto_init() }
func file_proto_kari_agent_v1_agent_proto_init() {
	if File_proto_kari_agent_v1_agent_proto != nil {
		return
	}
	file_proto_kari_agent_v1_agent_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_kari_agent_v1_agent_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kari_agent_v1_agent_proto_rawDesc), len(file_proto_kari_agent_v1_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kari_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_kari_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_proto_kari_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_proto_kari_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_kari_agent_v1_agent_proto = out.File
	file_proto_kari_agent_v1_agent_proto_goTypes = nil
	file_proto_kari_agent_v1_agent_proto_depIdxs = nil
}
