// proto/kari/agent/v1/agent.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/kari/agent/v1/agent.proto

package rustagent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemAgent_GetSystemStatus_FullMethodName       = "/kari.agent.v1.SystemAgent/GetSystemStatus"
	SystemAgent_ExecutePackageCommand_FullMethodName = "/kari.agent.v1.SystemAgent/ExecutePackageCommand"
	SystemAgent_ProvisionAppJail_FullMethodName      = "/kari.agent.v1.SystemAgent/ProvisionAppJail"
	SystemAgent_ManageService_FullMethodName         = "/kari.agent.v1.SystemAgent/ManageService"
	SystemAgent_StreamDeployment_FullMethodName      = "/kari.agent.v1.SystemAgent/StreamDeployment"
	SystemAgent_DeleteDeployment_FullMethodName      = "/kari.agent.v1.SystemAgent/DeleteDeployment"
	SystemAgent_TeardownJail_FullMethodName          = "/kari.agent.v1.SystemAgent/TeardownJail"
	SystemAgent_WriteSystemFile_FullMethodName       = "/kari.agent.v1.SystemAgent/WriteSystemFile"
	SystemAgent_InstallCertificate_FullMethodName    = "/kari.agent.v1.SystemAgent/InstallCertificate"
	SystemAgent_ApplyFirewallPolicy_FullMethodName   = "/kari.agent.v1.SystemAgent/ApplyFirewallPolicy"
	SystemAgent_ScheduleJob_FullMethodName           = "/kari.agent.v1.SystemAgent/ScheduleJob"
)

// SystemAgentClient is the client API for SystemAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemAgentClient interface {
	// 🛡️ SLA: Heartbeat & Resource Monitoring for the Brain's Prober
	GetSystemStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemStatus, error)
	// 📦 Execution & Isolation
	ExecutePackageCommand(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (*AgentResponse, error)
	ProvisionAppJail(ctx context.Context, in *ProvisionJailRequest, opts ...grpc.CallOption) (*AgentResponse, error)
	ManageService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*AgentResponse, error)
	// 🛡️ SLA Enforcement: Server-Side Streaming for Log Backpressure
	StreamDeployment(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
	// 🔥 Resource Teardown
	DeleteDeployment(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*AgentResponse, error)
	TeardownJail(ctx context.Context, in *TeardownRequest, opts ...grpc.CallOption) (*AgentResponse, error)
	// 🛠️ Filesystem & Infrastructure
	WriteSystemFile(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*AgentResponse, error)
	InstallCertificate(ctx context.Context, in *SslPayload, opts ...grpc.CallOption) (*AgentResponse, error)
	// 🛡️ Abstract Policy Intent
	ApplyFirewallPolicy(ctx context.Context, in *FirewallPolicy, opts ...grpc.CallOption) (*AgentResponse, error)
	ScheduleJob(ctx context.Context, in *JobIntent, opts ...grpc.CallOption) (*AgentResponse, error)
}

type systemAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemAgentClient(cc grpc.ClientConnInterface) SystemAgentClient {
	return &systemAgentClient{cc}
}

func (c *systemAgentClient) GetSystemStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemStatus)
	err := c.cc.Invoke(ctx, SystemAgent_GetSystemStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemAgentClient) ExecutePackageCommand(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentResponse)
	err := c.cc.Invoke(ctx, SystemAgent_ExecutePackageCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemAgentClient) ProvisionAppJail(ctx context.Context, in *ProvisionJailRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentResponse)
	err := c.cc.Invoke(ctx, SystemAgent_ProvisionAppJail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemAgentClient) ManageService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentResponse)
	err := c.cc.Invoke(ctx, SystemAgent_ManageService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemAgentClient) StreamDeployment(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemAgent_ServiceDesc.Streams[0], SystemAgent_StreamDeployment_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeployRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemAgent_StreamDeploymentClient = grpc.ServerStreamingClient[LogChunk]

func (c *systemAgentClient) DeleteDeployment(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentResponse)
	err := c.cc.Invoke(ctx, SystemAgent_DeleteDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemAgentClient) TeardownJail(ctx context.Context, in *TeardownRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentResponse)
	err := c.cc.Invoke(ctx, SystemAgent_TeardownJail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemAgentClient) WriteSystemFile(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentResponse)
	err := c.cc.Invoke(ctx, SystemAgent_WriteSystemFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemAgentClient) InstallCertificate(ctx context.Context, in *SslPayload, opts ...grpc.CallOption) (*AgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentResponse)
	err := c.cc.Invoke(ctx, SystemAgent_InstallCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemAgentClient) ApplyFirewallPolicy(ctx context.Context, in *FirewallPolicy, opts ...grpc.CallOption) (*AgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentResponse)
	err := c.cc.Invoke(ctx, SystemAgent_ApplyFirewallPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemAgentClient) ScheduleJob(ctx context.Context, in *JobIntent, opts ...grpc.CallOption) (*AgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentResponse)
	err := c.cc.Invoke(ctx, SystemAgent_ScheduleJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemAgentServer is the server API for SystemAgent service.
// All implementations must embed UnimplementedSystemAgentServer
// for forward compatibility.
type SystemAgentServer interface {
	// 🛡️ SLA: Heartbeat & Resource Monitoring for the Brain's Prober
	GetSystemStatus(context.Context, *Empty) (*SystemStatus, error)
	// 📦 Execution & Isolation
	ExecutePackageCommand(context.Context, *PackageRequest) (*AgentResponse, error)
	ProvisionAppJail(context.Context, *ProvisionJailRequest) (*AgentResponse, error)
	ManageService(context.Context, *ServiceRequest) (*AgentResponse, error)
	// 🛡️ SLA Enforcement: Server-Side Streaming for Log Backpressure
	StreamDeployment(*DeployRequest, grpc.ServerStreamingServer[LogChunk]) error
	// 🔥 Resource Teardown
	DeleteDeployment(context.Context, *DeleteRequest) (*AgentResponse, error)
	TeardownJail(context.Context, *TeardownRequest) (*AgentResponse, error)
	// 🛠️ Filesystem & Infrastructure
	WriteSystemFile(context.Context, *FileWriteRequest) (*AgentResponse, error)
	InstallCertificate(context.Context, *SslPayload) (*AgentResponse, error)
	// 🛡️ Abstract Policy Intent
	ApplyFirewallPolicy(context.Context, *FirewallPolicy) (*AgentResponse, error)
	ScheduleJob(context.Context, *JobIntent) (*AgentResponse, error)
	mustEmbedUnimplementedSystemAgentServer()
}

// UnimplementedSystemAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemAgentServer struct{}

func (UnimplementedSystemAgentServer) GetSystemStatus(context.Context, *Empty) (*SystemStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemStatus not implemented")
}
func (UnimplementedSystemAgentServer) ExecutePackageCommand(context.Context, *PackageRequest) (*AgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecutePackageCommand not implemented")
}
func (UnimplementedSystemAgentServer) ProvisionAppJail(context.Context, *ProvisionJailRequest) (*AgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionAppJail not implemented")
}
func (UnimplementedSystemAgentServer) ManageService(context.Context, *ServiceRequest) (*AgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManageService not implemented")
}
func (UnimplementedSystemAgentServer) StreamDeployment(*DeployRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Errorf(codes.Unimplemented, "method StreamDeployment not implemented")
}
func (UnimplementedSystemAgentServer) DeleteDeployment(context.Context, *DeleteRequest) (*AgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeployment not implemented")
}
func (UnimplementedSystemAgentServer) TeardownJail(context.Context, *TeardownRequest) (*AgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TeardownJail not implemented")
}
func (UnimplementedSystemAgentServer) WriteSystemFile(context.Context, *FileWriteRequest) (*AgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteSystemFile not implemented")
}
func (UnimplementedSystemAgentServer) InstallCertificate(context.Context, *SslPayload) (*AgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallCertificate not implemented")
}
func (UnimplementedSystemAgentServer) ApplyFirewallPolicy(context.Context, *FirewallPolicy) (*AgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyFirewallPolicy not implemented")
}
func (UnimplementedSystemAgentServer) ScheduleJob(context.Context, *JobIntent) (*AgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleJob not implemented")
}
func (UnimplementedSystemAgentServer) mustEmbedUnimplementedSystemAgentServer() {}
func (UnimplementedSystemAgentServer) testEmbeddedByValue()                     {}

// UnsafeSystemAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemAgentServer will
// result in compilation errors.
type UnsafeSystemAgentServer interface {
	mustEmbedUnimplementedSystemAgentServer()
}

func RegisterSystemAgentServer(s grpc.ServiceRegistrar, srv SystemAgentServer) {
	// If the following call pancis, it indicates UnimplementedSystemAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemAgent_ServiceDesc, srv)
}

func _SystemAgent_GetSystemStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAgentServer).GetSystemStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemAgent_GetSystemStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAgentServer).GetSystemStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemAgent_ExecutePackageCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAgentServer).ExecutePackageCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemAgent_ExecutePackageCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAgentServer).ExecutePackageCommand(ctx, req.(*PackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemAgent_ProvisionAppJail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionJailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAgentServer).ProvisionAppJail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemAgent_ProvisionAppJail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAgentServer).ProvisionAppJail(ctx, req.(*ProvisionJailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemAgent_ManageService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAgentServer).ManageService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemAgent_ManageService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAgentServer).ManageService(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemAgent_StreamDeployment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeployRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemAgentServer).StreamDeployment(m, &grpc.GenericServerStream[DeployRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemAgent_StreamDeploymentServer = grpc.ServerStreamingServer[LogChunk]

func _SystemAgent_DeleteDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAgentServer).DeleteDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemAgent_DeleteDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAgentServer).DeleteDeployment(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemAgent_TeardownJail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeardownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAgentServer).TeardownJail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemAgent_TeardownJail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAgentServer).TeardownJail(ctx, req.(*TeardownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemAgent_WriteSystemFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAgentServer).WriteSystemFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemAgent_WriteSystemFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAgentServer).WriteSystemFile(ctx, req.(*FileWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemAgent_InstallCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SslPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAgentServer).InstallCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemAgent_InstallCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAgentServer).InstallCertificate(ctx, req.(*SslPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemAgent_ApplyFirewallPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallPolicy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAgentServer).ApplyFirewallPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemAgent_ApplyFirewallPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAgentServer).ApplyFirewallPolicy(ctx, req.(*FirewallPolicy))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemAgent_ScheduleJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemAgentServer).ScheduleJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemAgent_ScheduleJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemAgentServer).ScheduleJob(ctx, req.(*JobIntent))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemAgent_ServiceDesc is the grpc.ServiceDesc for SystemAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kari.agent.v1.SystemAgent",
	HandlerType: (*SystemAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemStatus",
			Handler:    _SystemAgent_GetSystemStatus_Handler,
		},
		{
			MethodName: "ExecutePackageCommand",
			Handler:    _SystemAgent_ExecutePackageCommand_Handler,
		},
		{
			MethodName: "ProvisionAppJail",
			Handler:    _SystemAgent_ProvisionAppJail_Handler,
		},
		{
			MethodName: "ManageService",
			Handler:    _SystemAgent_ManageService_Handler,
		},
		{
			MethodName: "DeleteDeployment",
			Handler:    _SystemAgent_DeleteDeployment_Handler,
		},
		{
			MethodName: "TeardownJail",
			Handler:    _SystemAgent_TeardownJail_Handler,
		},
		{
			MethodName: "WriteSystemFile",
			Handler:    _SystemAgent_WriteSystemFile_Handler,
		},
		{
			MethodName: "InstallCertificate",
			Handler:    _SystemAgent_InstallCertificate_Handler,
		},
		{
			MethodName: "ApplyFirewallPolicy",
			Handler:    _SystemAgent_ApplyFirewallPolicy_Handler,
		},
		{
			MethodName: "ScheduleJob",
			Handler:    _SystemAgent_ScheduleJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDeployment",
			Handler:       _SystemAgent_StreamDeployment_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/kari/agent/v1/agent.proto",
}
