#!/usr/bin/env bash
# Karı - Docker Compose Integration Bootstrapper
# Validates the Zero-Trust Container Architecture locally.

set -euo pipefail

# --- Color formatting ---
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

DOCKER_COMPOSE_CMD="docker compose"
if ! docker compose version &>/dev/null; then
    DOCKER_COMPOSE_CMD="docker-compose"
fi

echo -e "${CYAN}======================================================${NC}"
echo -e "${CYAN}🐳 Booting Karı Containerized Integration Stack...${NC}"
echo -e "${CYAN}======================================================${NC}"

# 1. 🛡️ Environment Agnosticism Check
if [ ! -f "$ROOT_DIR/.env" ]; then
    echo -e "${YELLOW}⚠️ No .env file found. Generating a secure local testing configuration...${NC}"
    cat <<EOF > "$ROOT_DIR/.env"
# Auto-generated by up.sh for local integration testing
DB_PASSWORD=kari_integration_secure_pass_2026
JWT_SECRET=$(openssl rand -hex 32)
EOF
    echo -e "${GREEN}✅ .env created with secure random JWT secret.${NC}"
fi

# 2. 🛡️ Pre-Flight Network & Volume Cleanup
# Ensures we don't have dangling sockets from a previous crashed run
echo -e "${YELLOW}🧹 Cleaning up previous state...${NC}"
$DOCKER_COMPOSE_CMD down --remove-orphans &>/dev/null || true

# 3. 🛡️ Bootstrapping the Stack
echo -e "${YELLOW}🏗️ Building and launching Docker Compose stack...${NC}"
# --build ensures our multi-stage Dockerfiles are freshly compiled
# -d runs them in the background so we can control log streaming
$DOCKER_COMPOSE_CMD up --build -d

# 4. 🛡️ Health & SLA Verification
echo -e "${YELLOW}⏳ Waiting for Database and Brain to achieve readiness...${NC}"

# Wait for the Go Brain to become healthy (which inherently waits for the DB)
MAX_RETRIES=30
COUNT=0
until [ "$($DOCKER_COMPOSE_CMD ps -q api 2>/dev/null | xargs -r docker inspect -f '{{.State.Status}}')" == "running" ] || [ $COUNT -eq $MAX_RETRIES ]; do
    sleep 1
    ((COUNT++))
done

if [ $COUNT -eq $MAX_RETRIES ]; then
    echo -e "${RED}❌ Integration stack failed to stabilize.${NC}"
    $DOCKER_COMPOSE_CMD logs
    exit 1
fi

echo -e "${GREEN}======================================================${NC}"
echo -e "${GREEN}🎉 Container Stack is Live!${NC}"
echo -e "    🌐 SvelteKit UI:  ${CYAN}http://localhost:3000${NC}"
echo -e "    🧠 Go Brain API:  ${CYAN}Isolated on backplane (Proxied via UI)${NC}"
echo -e "    ⚙️ Rust Muscle:   ${CYAN}Running as privileged container${NC}"
echo -e "${GREEN}======================================================${NC}"
echo -e "Streaming logs... (Press ${RED}Ctrl+C${NC} to stop and destroy containers)\n"

# 5. 🛡️ Graceful Teardown Trap
cleanup() {
    echo -e "\n${RED}🛑 Tearing down integration stack...${NC}"
    $DOCKER_COMPOSE_CMD down
    echo -e "${GREEN}✅ Stack destroyed safely. Goodbye!${NC}"
    exit 0
}

trap cleanup SIGINT SIGTERM

# Stream logs from all containers beautifully multiplexed
$DOCKER_COMPOSE_CMD logs -f
